project:
  type: website
  output-dir: docs

website:
  title: "Smrithi Sunil"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: posts.qmd
        text: Blog
      - href: /images/SmrithiSunil_CV.pdf
        text: CV
      - contact.qmd
  body-footer: |
    <!-- 100% privacy-first analytics -->
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>

format:
  html:
    theme: flatly
    css: styles.scss
    toc: true



