project:
  type: website
  output-dir: docs

website:
  title: "Smrithi Sunil"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



