project:
  type: website
  output-dir: docs

website:
  title: "Smrithi Sunil"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - posts.qmd
      - href: CV.qmd
        text: CV
      - contact.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



