project:
  type: website
  output-dir: docs

website:
  title: "Smrithi Sunil"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: posts.qmd
        text: Blog
      - href: /images/SmrithiSunil_CV.pdf
        text: CV
      - contact.qmd

format:
  html:
    theme: flatly
    css: styles.scss
    toc: true



