project:
  type: website
  output-dir: docs

website:
  title: "Smrithi Sunil"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: posts.qmd
        text: Blog
      - href: /images/SmrithiSunil_CV.pdf
        text: CV
      - contact.qmd
  body-footer: |
    <script data-goatcounter="https://smrithisunil.goatcounter.com/count"
            async src="//gc.zgo.at/count.js"></script>
  twitter-card: true
  site-url: https://smrithisunil.com

format:
  html:
    theme: flatly
    css: styles.scss
    toc: true



